services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event_loader_app
    volumes:
      - ./:/app
    depends_on:
      - redis
    environment:
      APP_ENV: dev
      LOCK_DSN: redis://redis:6379
      REDIS_URL: redis://redis:6379

  redis:
    image: redis:7-alpine
    container_name: event_loader_redis
    ports:
      - "6379:6379"
